version: "3.3"

services:
    # Start local Postgres
    database:
        image: "postgres:14.8-alpine"
        ports:
            - "5432:5432"
        expose:
            - 5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=ports
        volumes:
            - "./.postgres-data/db:/var/lib/postgresql"
        networks:
            - app-network

    app:
        build: .
        depends_on:
            - database
        networks:
            - app-network
        environment:
            - DATABASE_URL=postgres://admin:admin@database:5432/ports?sslmode=disable

networks:
  app-network:
    driver: bridge